### PR TITLE
Added isValidEmail & getInitials extension method on String

### PR DESCRIPTION
**Pull request by ahmeddhus**
## Description

- Add isValidEmailt extension which checks if the string is a valid email or not with an option to check with a specific pattern.
- Get name initial characters from a String

## Basic Checklist

- [x] ✨ Ran `dartdoc`
- [x] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new extension, added in Readme and example too

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by AbhishekDoshi26** [comment]
Hey @ahmeddhus this is a very good use case. But I feel everyone has different requirements for email. Hence, it shouldn't be a generalized feature in the package. WDYT?

**Comment by ahmeddhus** [comment]
Hello @AbhishekDoshi26, yes I agree and that's why I added a pattern parameter for customization purposes.
I'm thinking if we can make the pattern more general.
but I understand what you mean now

**Comment by AbhishekDoshi26** [comment]
@ahmeddhus why did you close the PR?

**Comment by ahmeddhus** [comment]
Sorry by mistake, Just added another extension to get initials from a string that we can you with names plus update the description @AbhishekDoshi26

**Comment by AbhishekDoshi26** [comment]
@ahmeddhus please update the readme as well. Will wait for the PR to merge as #11 is a priority right now. Once that PR is merged, you might need to write unit test for this extension as well :)

**Review by AbhishekDoshi26 — APPROVED** [review]

**Comment by CoderNamedHendrick** [comment]
@ahmedhusZ please could you merge your changes as they have been approved.

**Review by AbhishekDoshi26 — CHANGES_REQUESTED** [review]
Update Readme.md

**Comment by AbhishekDoshi26** [comment]
@CoderNamedHendrick no. This PR won't be merged as of now as there needs to be some changes needed

**Comment by ahmeddhus** [comment]
Just updated Readme.md, @AbhishekDoshi26 
Feel free to ask me if you want any help with the unit test, @CoderNamedHendrick

**Review by AbhishekDoshi26 — APPROVED** [review]

**Pull request merged**
