### PR TITLE
feature: unit tests for super extensions.

### PR DESCRIPTION
**Pull request by CoderNamedHendrick**
## Description

Unit Tests for extension functions

## Basic Checklist

- [ ] ✨ Ran `dartdoc`
- [ ] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new extension, added in Readme and example too

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [x] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [x] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [x] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by CoderNamedHendrick** [comment]
#9

**Comment by CoderNamedHendrick** [comment]
@AbhishekDoshi26  I noticed a bug with the capitaliseFirstChar() extension function when I was running the tests which I fixed.

**Comment by AbhishekDoshi26** [comment]
@CoderNamedHendrick thanks for the fix and unit-tests. There are many other extension methods and it would be good to have test cases for each of them.

If you need help, let me know :)

**Comment by CoderNamedHendrick** [comment]
@AbhishekDoshi26  for the navigation tests I might need some help with that. Do we need to create a sample app to test them?

**Comment by CoderNamedHendrick** [comment]
Seen the issue with the build. Resolving it atm

**Comment by AbhishekDoshi26** [comment]
@CoderNamedHendrick thanks for all the work. Please take a pull from main. I won't merge any new PRs until the unit tests are in. Future contributors will write their own test cases.

**Comment by CoderNamedHendrick** [comment]
@ahmeddhus I might need some help writing tests for the navigation functions. Please could you help with that? Those are the only tests that are left for now, already wrote the unit tests for the newly added string-extension functions

**Comment by CoderNamedHendrick** [comment]
> @CoderNamedHendrick thanks for all the work. Please take a pull from main. I won't merge any new PRs until the unit tests are in. Future contributors will write their own test cases.

I should push the rest of the test cases today. I just need to do some work at my full-time job

**Comment by CoderNamedHendrick** [comment]
@AbhishekDoshi26  I've written tests for all the functions now. I noticed some bugs with some failing tests which I fixed and I added a new extension method to build context extensions.
I also ensured 100% test coverage for the lines of code.
@ahmeddhus

**Review by AbhishekDoshi26 — APPROVED** [review]
LGTM!
Thanks for the great work!

**Comment by CoderNamedHendrick** [comment]
> LGTM! Thanks for the great work!

Looking to contribute more and I'm happy to help

**Pull request merged**
