### PR TITLE
Feat: ext `hideSnackBar`

### PR DESCRIPTION
**Pull request by coder-Aayush**
## Basic Checklist

- [x] ✨ Ran `dartdoc`
- [x] 🛠️ Added proper documentation
- [x] ❌ No warnings or errors in the code
- [x] ✅ If added a new extension, added in Readme and example too
- [] 🧪 If added a new extension, written proper test cases for it

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Review by AbhishekDoshi26 — CHANGES_REQUESTED** [review]
The functionality looks good, please add test cases, example and documentation in README.md

**Comment by AbhishekDoshi26** [comment]
@coder-Aayush please fix the PR

**Comment by coder-Aayush** [comment]
> @coder-Aayush please fix the PR

okay

**Comment by AbhishekDoshi26** [comment]
@coder-Aayush pipeline is failing

**Comment by AbhishekDoshi26** [comment]
Closed as owner isn't working.

**Pull request closed without merging**
